version: '{build}'
image:
  - Visual Studio 2019
  - Ubuntu
stack: node 6
skip_commits:
  files:
    - '*.md'
    - '*.txt'
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- ps: if ($isWindows) { Install-Product node 6 }
- cmd: npm install -g eclint
- cmd: git rm .editorconfig
- cmd: eclint check -n "**/*.{cs,tt,cmd,sh,md,txt,yml}"
- cmd: eclint check -w "**/*.{cs,tt,cmd,sh,md,txt,yml,json,sln,csproj,shfbproj}"
- cmd: git reset --hard
- cmd: curl -OsSL https://dot.net/v1/dotnet-install.ps1
- ps: if ($isWindows) { ./dotnet-install.ps1 -JsonFile global.json }
- sh: curl -OsSL https://dot.net/v1/dotnet-install.sh
- sh: chmod +x dotnet-install.sh
- sh: ./dotnet-install.sh --jsonfile global.json
- sh: ./dotnet-install.sh --runtime dotnet --version 2.1.15 --skip-non-versioned-files
- sh: export PATH="$HOME/.dotnet:$PATH"
skip_tags: true
before_build:
- dotnet --info
build_script:
- ps: |
    $id = ([datetimeoffset]$env:APPVEYOR_REPO_COMMIT_TIMESTAMP).ToUniversalTime().ToString('yyyyMMdd''t''HHmm')
    if ($isWindows) {
        cmd /c call .\pack.cmd ci-$id $env:APPVEYOR_REPO_COMMIT
    } else {
        ./pack.sh  ci-$id $env:APPVEYOR_REPO_COMMIT
    }
test_script:
- cmd: test.cmd
- ps: if ($isWindows) { Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe }
- cmd: codecov.exe
- sh: ./test.sh
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
