version: '{build}'
image: Visual Studio 2017
skip_commits:
  files:
    - '*.md'
    - '*.txt'
skip_tags: true
install:
- ps: Install-Product node 6
- npm install -g eclint
- git rm .editorconfig
- eclint check -n "**/*.{cs,tt,cmd,sh,md,txt,yml}"
- eclint check -w "**/*.{cs,tt,cmd,sh,md,txt,yml,json,sln,csproj,shfbproj}"
- git reset --hard
build_script:
- ps: >-
    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    .\pack.cmd ci-$id $env:APPVEYOR_REPO_COMMIT
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
