// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 03 Jul 2018 09:22:55 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.22203.0")]
[assembly: AssemblyFileVersion("1.0.22203.922")]