// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 19 May 2016 11:08:45 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19619.0")]
[assembly: AssemblyFileVersion("1.0.19619.1108")]