// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 12 Aug 2016 09:59:41 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19912.0")]
[assembly: AssemblyFileVersion("1.0.19912.959")]